### PR TITLE
Rename IsIterable to IsIterator

### PR DESCRIPTION
**Pull request by davidanthoff**
This seems more in line with how folks talk about iterators in the base documentation. It will also help me in the way I am using this trait in Query.jl and my plans there (too long and complicated too explain ;).

### CODE REVIEW

**Comment by mauro3** [comment]
Either way is fine.  But the earliest I would tag a new version is the end of the week as there was a lot of churn for Tony to work through recently.

**Comment by davidanthoff** [comment]
No worry about timing, I'm happy if this is just on ``master`` for now, the things I'm doing in Query right now will take a while in any case.

**Comment by davidanthoff** [comment]
Thanks!

**Comment by davidanthoff** [comment]
@mauro3 Actually, any chance you could tag a version now? I'm essentially at a point where I could release a lot of stuff that uses this.

**Pull request merged**
