### PR TITLE
Fix 0.5 deprecations and breakages

### PR DESCRIPTION
**Pull request by timholy**
I'm playing with different traits implementations (this one and Traitor), and noticed a few things to update for Julia 0.5. There's still a warning about an overwritten method that I haven't looked into.

### CODE REVIEW

**Comment by mauro3** [comment]
Cool, thanks!

Note I did some more work on this on which is sitting in PR #2. I think its mostly ready to merge but I ran out of time.  Let me know if this looks interesting to you and I'll try and finish it.

**Comment by timholy** [comment]
I didn't look at it seriously, but :+1: to the idea of being able to dispatch on multiple traits at once.

With regards to whether to merge #2, FYI I am starting to use this package in a rewrite of Images. (See one small piece of this---currently the only part that is using traits---at https://github.com/JuliaImages/ImagesAxes.jl.) One option is to see if whether I (or anyone else) actually comes up with a concrete use for the fancy things that #2 allows, and then if so that becomes good incentive to work on it and merge it.

One thing that is foreseeable is that if I'm going to base a rewrite of Images on SimpleTraits, I'll need it to be registered as a package.

**Comment by mauro3** [comment]
Yay, the first user!  Yes, keep me in the loop on how that goes.  And yes, I can register it.  Should I do it now or is there no hurry? 

Question: are you using multi-parameter traits or is there another reason why you prefer this of Traitor?

**Comment by timholy** [comment]
No immediate hurry, certainly not in the next week or so. It's a pretty big rewrite :smile:.

Regarding the comparison with Traitor, I confess I like Traitor's syntax better (disclaimer: I was the one who initially suggested that syntax in a discussion at JuliaCon, so I'm rather biased). But Traitor doesn't really work in practice yet; I actually started ImagesAxes with Traitor and discovered some bugs that prevented me from doing some of what I wanted to do. Given the many things I need to do, I decided that expediency wins, and this package is fully functional.

I'm also well aware of how long and hard you've thought about traits, so I decided it was high time to start using your excellent work in a real-life application :smile:.

**Comment by mauro3** [comment]
Tnx!  I think it should be reasonably easy to add support for the Traitor syntax.  Although, I don't have time to do it at the moment.

**Pull request merged**
